name: ci
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
    minimal-reproducer:
        env:
            foo: bar
            create_log_artifact_on_success: 1
        strategy:
            matrix:
                debug: [0, 1, 2, 3]
        name: reproducer
        environment: CI
        runs-on: ubuntu-latest
        timeout-minutes: 2
        steps:
          - name: Check out hw
            id: checkout-hw
            uses: actions/checkout@v4

          - name: Setup Docker Compose
            id: setup-docker-compose
            uses: docker/setup-compose-action@v2
            with:
              version: latest

          - name: Build container image
            id: build-container
            run: |
              docker compose -f ./containers/docker-compose.yml --progress=plain build

          - name: Bring container up
            id: container-up
            run: |
              docker compose -f ./containers/docker-compose.yml up -d

          - name: Test variable expansion
            id: variable-expansion-test
            run: |
               docker exec mycontainer bash -c "echo Hello World! env.debug=${{ matrix.debug }}"
               docker exec mycontainer bash -c "echo Hello World! env.create_log_artifact_on_success=${{ env.create_log_artifact_on_success }}"
               docker exec mycontainer bash -c "echo Hello World! env.DEBUG_LEVELS=${{ vars.DEBUG_LEVELS }}"

          - name: Bring container down
            id: container-down
            continue-on-error: true
            run: |
              docker compose -f ./containers/docker-compose.yml down

